#!/usr/bin/env python3
"""AI Reviewer pack generator for PRs (advisory).

Produces a structured review checklist/report from changed files and EOS rules.
In CI, this writes an artifact that humans/AI can complete; it also fails soft unless --strict.
"""

from __future__ import annotations

import argparse
import subprocess

from eos_lib import ROOT, meta_block

OUT = ROOT / "metrics" / "AI_REVIEW.generated.md"


def git_diff_names() -> list[str]:
    try:
        base = subprocess.check_output(
            ["git", "diff", "--name-only", "HEAD~1", "HEAD"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        )
        files = [line.strip() for line in base.splitlines() if line.strip()]
        if files:
            return files
    except Exception:
        pass
    try:
        out = subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        )
        files = []
        for line in out.splitlines():
            if len(line) > 3:
                files.append(line[3:].strip())
        return files
    except Exception:
        return []


def classify(files: list[str]) -> dict:
    buckets = {
        "architecture": [],
        "security": [],
        "standards": [],
        "documentation": [],
        "api_events": [],
        "implementation": [],
        "other": [],
    }
    for f in files:
        fl = f.lower()
        if any(x in fl for x in ["04 solution", "19 reference", "20 domain", "adr", "architecture"]):
            buckets["architecture"].append(f)
        elif any(x in fl for x in ["10 security", "security", "ai/07_security"]):
            buckets["security"].append(f)
        elif any(x in fl for x in ["21 technical", "22 engineering", "ai/08_standards", "ai/rules"]):
            buckets["standards"].append(f)
        elif fl.startswith("07 ") or fl.startswith("08 ") or "openapi" in fl or "events.yaml" in fl:
            buckets["api_events"].append(f)
        elif fl.startswith("implementation/"):
            buckets["implementation"].append(f)
        elif fl.endswith(".md") or fl.startswith("docs/") or fl.startswith("ai/"):
            buckets["documentation"].append(f)
        else:
            buckets["other"].append(f)
    return buckets


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="Exit 2 if implementation changes lack docs/catalog touch")
    args = parser.parse_args()

    files = git_diff_names()
    buckets = classify(files)

    lines = [
        "# AI Review Report (Advisory)",
        "",
        *meta_block("EOS-AIREV-001"),
        "> Generated by `tools/ai_reviewer.py`. Use with prompts in `ai-platform/prompts/`.",
        "",
        "## Changed Files",
        "",
    ]
    if not files:
        lines.append("_No git changes detected in this environment._")
    else:
        for f in files:
            lines.append(f"- `{f}`")

    lines += ["", "## Review Lanes", ""]
    for lane, items in buckets.items():
        lines.append(f"### {lane}")
        if not items:
            lines.append("- —")
        else:
            for i in items:
                lines.append(f"- `{i}`")
        lines.append("")

    lines += [
        "## Mandatory Checks",
        "",
        "- [ ] Architecture: domain boundaries respected"
        " (`ai-platform/prompts/architecture-review/v1/prompt.md`)",
        "- [ ] Security: authz/PII/audit considered"
        " (`ai-platform/prompts/security-review/v1/prompt.md`)",
        "- [ ] Coding Standard: handbook/standards followed"
        " (`ai-platform/prompts/code-review/v1/prompt.md`)",
        "- [ ] Documentation: EKR/AI context synced"
        " (`ai-platform/prompts/sync-docs/v1/prompt.md`)",
        "- [ ] API/Event: catalogs updated if contracts changed",
        "- [ ] Traceability: links updated if BR/FR/API/Event/Test changed",
        "",
        "## Suggested AI Prompt Bundle",
        "",
        "1. `ai-platform/prompts/architecture-review/v1/prompt.md`",
        "2. `ai-platform/prompts/security-review/v1/prompt.md`",
        "3. `ai-platform/prompts/code-review/v1/prompt.md`",
        "4. `ai-platform/prompts/sync-docs/v1/prompt.md`",
        "",
    ]

    # soft quality heuristic
    impl = buckets["implementation"]
    docsish = buckets["documentation"] + buckets["api_events"] + buckets["architecture"]
    warning = bool(impl) and not docsish
    if warning:
        lines += [
            "## Warning",
            "",
            "Implementation files changed without documentation/catalog/architecture updates detected.",
            "Verify whether docs sync is required before merge.",
            "",
        ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    if args.strict and warning:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
