#!/usr/bin/env python3
"""AI Memory Builder: generate compact structured summaries for AI assistants."""

from __future__ import annotations

import shutil
from pathlib import Path

from aip_lib import AIP, current_memory_version
from eos_lib import (
    ROOT,
    domain_signals,
    list_events,
    list_openapi_ops,
    load_traceability,
    meta_block,
)

LEGACY_OUT = ROOT / "ai" / "generated"


def out_dir() -> Path:
    ver = current_memory_version()
    path = AIP / "memory" / ver
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_snippet(path: Path, max_chars: int = 1200) -> str:
    if not path.exists():
        return "_Not available yet._"
    text = path.read_text(encoding="utf-8", errors="ignore")
    parts = text.split("\n\n", 2)
    body = parts[-1] if len(parts) > 1 else text
    body = body.strip()
    if len(body) > max_chars:
        return body[:max_chars].rstrip() + "\n\n_…truncated…_"
    return body


def write_global(links, artifacts, directory: Path):
    out = directory / "memory_global.md"
    lines = [
        "# AI Memory — Global",
        "",
        *meta_block("AI-MEM-GLOBAL"),
        "> Generated by `tools/build_ai_memory.py`. Do not edit manually.",
        f"> Version root: `{directory.relative_to(ROOT).as_posix()}`",
        "",
        "## Project Snapshot",
        "",
        read_snippet(ROOT / "ai" / "00_project.md", 900),
        "",
        "## Business Snapshot",
        "",
        read_snippet(ROOT / "ai" / "01_business.md", 900),
        "",
        "## Architecture Snapshot",
        "",
        read_snippet(ROOT / "ai" / "02_architecture.md", 900),
        "",
        "## Hard Rules (must obey)",
        "",
        read_snippet(AIP / "policies" / "ai-rules.md", 1200)
        if (AIP / "policies" / "ai-rules.md").exists()
        else read_snippet(ROOT / "ai" / "rules.md", 1200),
        "",
        "## Catalog Counts",
        "",
        f"- Traceability links: {len(links)}",
        f"- OpenAPI specs: {len(list_openapi_ops())}",
        f"- Events: {len(list_events())}",
        f"- FR artifacts referenced: {len(artifacts.get('fr', {}))}",
        f"- BR artifacts referenced: {len(artifacts.get('br', {}))}",
        "",
        "## Active Implementation Focus",
        "",
        "- Sprint-01: Foundation & ECMF Case Core",
        "- Sprint-02: Assignment, Status, Notification Hook",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def write_domain_memory(domain: str, directory: Path):
    sig = domain_signals(domain)
    slug = domain.lower().replace(" ", "-")
    out = directory / f"memory_{slug}.md"
    pack = AIP / "packs" / slug / "pack.md"
    lines = [
        f"# AI Memory — Domain {domain}",
        "",
        *meta_block(f"AI-MEM-{domain.upper().replace(' ', '')[:12]}"),
        "> Generated by `tools/build_ai_memory.py`. Do not edit manually.",
        "",
        "## Domain Context",
        "",
        read_snippet(sig["ai_domain"], 1600),
        "",
        "## Domain Pack",
        "",
        read_snippet(pack, 1200) if pack.exists() else "_Pack not available._",
        "",
        "## Coverage Snapshot",
        "",
        f"- Business context: {'✅' if sig['business'] else '❌'}",
        f"- FRD score: {sig['frd_score']}%",
        f"- API score: {sig['api_score']}%",
        f"- Event score: {sig['event_score']}%",
        f"- Test score: {sig['test_score']}%",
        "",
        "## Linked Artifacts",
        "",
        f"- BR: {', '.join(f'`{x}`' for x in sig['brs']) or '—'}",
        f"- FR: {', '.join(f'`{x}`' for x in sig['frs']) or '—'}",
        f"- API: {', '.join(f'`{x}`' for x in sig['apis']) or '—'}",
        f"- Events: {', '.join(f'`{x}`' for x in sig['events']) or '—'}",
        f"- Tests: {', '.join(f'`{x}`' for x in sig['tests']) or '—'}",
        f"- Sprints: {', '.join(f'`{x}`' for x in sig['sprints']) or '—'}",
        "",
        "## Architecture Notes",
        "",
        read_snippet(sig["arch"], 1000),
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def write_index(files, directory: Path):
    out = directory / "README.md"
    lines = [
        "# Generated AI Memory",
        "",
        *meta_block("AI-MEM-000"),
        "> Generated summaries for ChatGPT / Claude / Cursor.",
        f"> Canonical root: `ai-platform/memory/{current_memory_version()}/`",
        "> Refresh via `python tools/eos.py memory`.",
        "",
        "## Files",
        "",
    ]
    for f in files:
        lines.append(f"- `{f.relative_to(ROOT).as_posix()}`")
    lines += [
        "",
        "## Usage",
        "",
        "1. Always load `ai-platform/policies/ai-rules.md`",
        f"2. Load `ai-platform/memory/{current_memory_version()}/memory_global.md`",
        "3. Load domain memory / domain pack for the active domain",
        "4. Load active sprint file under `ai/sprint/`",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def sync_legacy(directory: Path):
    """Keep ai/generated as compatibility mirror."""
    LEGACY_OUT.mkdir(parents=True, exist_ok=True)
    for src in directory.glob("memory_*.md"):
        shutil.copy2(src, LEGACY_OUT / src.name)
    readme = directory / "README.md"
    if readme.exists():
        shutil.copy2(readme, LEGACY_OUT / "README.md")


def main():
    directory = out_dir()
    links, artifacts = load_traceability()
    files = [write_global(links, artifacts, directory)]
    for domain in ["CRM", "ECMF", "KPI", "Dashboard", "Notification", "Core Platform"]:
        files.append(write_domain_memory(domain, directory))
    files.append(write_index(files, directory))
    sync_legacy(directory)
    print("AI Memory Builder")
    print(f"- version: {current_memory_version()}")
    for f in files:
        print(f"- wrote {f}")
    print(f"- synced legacy mirror -> {LEGACY_OUT}")


if __name__ == "__main__":
    main()
