#!/usr/bin/env python3
"""Documentation Coverage dashboard per domain."""

from __future__ import annotations

from eos_lib import ROOT, domain_signals, meta_block

OUT = ROOT / "00 Repository Guide" / "DOC_COVERAGE.generated.md"
PORTAL = ROOT / "docs" / "governance" / "doc-coverage.md"


def mark(score: int | bool) -> str:
    if isinstance(score, bool):
        return "✅" if score else "❌"
    if score >= 80:
        return f"✅ {score}%"
    if score >= 40:
        return f"🟡 {score}%"
    if score > 0:
        return f"🟠 {score}%"
    return f"❌ {score}%"


def main():
    domains = ["CRM", "ECMF", "KPI", "Dashboard", "Notification", "Core Platform"]
    rows = [domain_signals(d) for d in domains]

    lines = [
        "# Documentation Coverage",
        "",
        *meta_block("EOS-COV-001"),
        "> Generated by `tools/doc_coverage.py`.",
        "",
        "| Domain | Business | FRD | API | Event | Test |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['domain']} | {mark(r['business'])} | {mark(r['frd_score'])} | "
            f"{mark(r['api_score'])} | {mark(r['event_score'])} | {mark(r['test_score'])} |"
        )

    lines += [
        "",
        "## Interpretation",
        "",
        "- ✅ Business = domain AI/architecture context exists",
        "- FRD/API/Event/Test scores are heuristic from traceability + catalog presence",
        "- Improve by adding FRD docs, OpenAPI ops, events, and tests linked in `traceability.yaml`",
        "",
        "## Priority Gaps",
        "",
    ]
    gaps = []
    for r in rows:
        score = (r["frd_score"] + r["api_score"] + r["event_score"] + r["test_score"]) / 4
        gaps.append((score, r["domain"], r))
    for score, domain, r in sorted(gaps, key=lambda x: x[0]):
        lines.append(
            f"- **{domain}** (avg {score:.0f}%) — FRD {r['frd_score']}%, API {r['api_score']}%, "
            f"Event {r['event_score']}%, Test {r['test_score']}%"
        )
    lines.append("")

    text = "\n".join(lines)
    OUT.write_text(text, encoding="utf-8")
    PORTAL.parent.mkdir(parents=True, exist_ok=True)
    PORTAL.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Wrote {PORTAL}")


if __name__ == "__main__":
    main()
