#!/usr/bin/env python3
"""Domain Navigator: generate one-stop domain packs."""

from __future__ import annotations


from eos_lib import ROOT, domain_signals, list_adrs, meta_block

OUT_DIR = ROOT / "20 Domain Architecture" / "navigator"
PORTAL_DIR = ROOT / "docs" / "navigator"


def render_domain(domain: str) -> str:
    sig = domain_signals(domain)
    adrs = list_adrs()
    lines = [
        f"# Domain Navigator — {domain}",
        "",
        *meta_block(f"EOS-NAV-{domain.upper().replace(' ', '')[:10]}"),
        f"> Generated by `tools/domain_navigator.py`. Command concept: _Masuk ke domain {domain}_",
        "",
        "## Quick Pack",
        "",
        f"- Domain Architecture: `{sig['arch'].relative_to(ROOT).as_posix() if sig['arch'].exists() else 'missing'}`",
        f"- AI Domain Context: `{sig['ai_domain'].relative_to(ROOT).as_posix() if sig['ai_domain'].exists() else 'missing'}`",
        f"- AI Memory: `ai/generated/memory_{domain.lower().replace(' ', '-')}.md`",
        "",
        "## Business Rules",
        "",
    ]
    if sig["brs"]:
        for br in sig["brs"]:
            lines.append(f"- `{br}`")
    else:
        lines.append("- — (belum tertaut di traceability)")

    lines += ["", "## FRD", ""]
    if sig["frs"]:
        for fr in sig["frs"]:
            lines.append(f"- `{fr}`")
    else:
        lines.append("- —")

    lines += ["", "## API", ""]
    lines += [f"- `{a}`" for a in sig["apis"]] or ["- —"]

    lines += ["", "## Events", ""]
    lines += [f"- `{e}`" for e in sig["events"]] or ["- —"]

    lines += ["", "## Tests", ""]
    lines += [f"- `{t}`" for t in sig["tests"]] or ["- —"]

    lines += ["", "## Active / Related Sprints", ""]
    lines += [f"- `{s}`" for s in sig["sprints"]] or ["- —"]

    lines += ["", "## ADR", ""]
    if adrs:
        for adr in adrs:
            lines.append(f"- `{adr['id']}` — `{adr['path'].relative_to(ROOT).as_posix()}`")
    else:
        lines.append("- — (belum ada ADR bernomor)")

    lines += [
        "",
        "## Coverage",
        "",
        "| Business | FRD | API | Event | Test |",
        "|---|---|---|---|---|",
        f"| {'✅' if sig['business'] else '❌'} | {sig['frd_score']}% | {sig['api_score']}% | {sig['event_score']}% | {sig['test_score']}% |",
        "",
        "## Traceability Links",
        "",
    ]
    if not sig["links"]:
        lines.append("- —")
    else:
        for link in sig["links"]:
            lines.append(f"- `{link.get('id')}` — {link.get('description')}")
    lines.append("")
    return "\n".join(lines)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    PORTAL_DIR.mkdir(parents=True, exist_ok=True)
    domains = ["CRM", "ECMF", "KPI", "Dashboard", "Notification", "Core Platform"]
    index = [
        "# Domain Navigator Index",
        "",
        *meta_block("EOS-NAV-000"),
        "> Generated by `tools/domain_navigator.py`.",
        "",
        "Ask: **Masuk ke domain <NAME>** → buka file navigator domain tersebut.",
        "",
        "| Domain | Navigator |",
        "|---|---|",
    ]
    for domain in domains:
        content = render_domain(domain)
        slug = domain.lower().replace(" ", "-")
        out = OUT_DIR / f"{slug}.md"
        portal = PORTAL_DIR / f"{slug}.md"
        out.write_text(content, encoding="utf-8")
        portal.write_text(content, encoding="utf-8")
        index.append(f"| {domain} | [{slug}.md](./{slug}.md) |")
        print(f"wrote {out}")
    index.append("")
    (OUT_DIR / "README.md").write_text("\n".join(index), encoding="utf-8")
    (PORTAL_DIR / "index.md").write_text("\n".join(index), encoding="utf-8")
    print(f"wrote {OUT_DIR / 'README.md'}")


if __name__ == "__main__":
    main()
