#!/usr/bin/env python3
"""ECMP EAR self-governance checker: health, metadata, links, ADR index, inventory."""

from __future__ import annotations

import argparse
import re
from datetime import date, datetime
from pathlib import Path

from repo_check_lib import (
    META_FIELDS,
    build_inventory,
    check_links,
    iter_markdown_files,
    parse_metadata,
    score_health,
)

ROOT = Path(__file__).resolve().parents[1]


def parse_date(value: str):
    value = (value or "").strip()
    if not value or value.lower() in {"auto", "tbd", "yyyy-mm-dd"}:
        return None
    for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            continue
    return None


def collect_adrs(root: Path):
    adr_dir = root / "05 Architecture Decision Records"
    rows = []
    if not adr_dir.exists():
        return rows
    for path in sorted(adr_dir.glob("*.md")):
        if path.name.upper().startswith("ADR-TEMPLATE") or path.name == "README.md":
            continue
        if "template" in path.name.lower() or path.name.endswith(".generated.md"):
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        meta = parse_metadata(text)
        adr_id = meta.get("ID", "")
        if not re.match(r"^ADR-\d{3,}$", adr_id, flags=re.IGNORECASE):
            continue
        # Ignore placeholder folder IDs like ADR-000
        if adr_id.upper() in {"ADR-000"}:
            continue
        rows.append(
            {
                "id": adr_id,
                "title": path.stem,
                "status": meta.get("Status", "n/a"),
                "owner": meta.get("Owner", "n/a"),
                "last_review": meta.get("Last Review", "n/a"),
                "path": path.relative_to(root).as_posix(),
            }
        )
    return rows


def template_usage(root: Path):
    templates_dir = root / "24 Templates"
    if not templates_dir.exists():
        return [], []
    templates = [p for p in templates_dir.glob("*") if p.is_file() and p.suffix in {".md", ".yaml", ".yml"}]
    unused = []
    used = []
    corpus = []
    for path in iter_markdown_files(root):
        if "24 Templates" in path.parts:
            continue
        corpus.append(path.read_text(encoding="utf-8", errors="ignore"))
    blob = "\n".join(corpus)
    for tpl in templates:
        token = tpl.name
        stem = tpl.stem
        if token in blob or stem in blob or f"Templates/{token}" in blob or f"Templates\\{token}" in blob:
            used.append(tpl.name)
        else:
            # document header template is referenced by standard name variations
            if stem in {"DOCUMENT_HEADER_TEMPLATE", "ADR_TEMPLATE", "FRD_TEMPLATE"}:
                used.append(tpl.name)
            else:
                unused.append(tpl.name)
    return used, unused


def write_health_report(root: Path, stats: dict, inventory, missing_details, adrs, unused_templates):
    out = root / "00 Repository Guide" / "REPO_HEALTH_REPORT.md"
    today = date.today().isoformat()
    lines = [
        "# Repository Health Report",
        "",
        "| Field | Value |",
        "|---|---|",
        "| ID | EAR-IDX-005 |",
        "| Version | 0.1 |",
        "| Owner | Automation |",
        "| Reviewer | PMO / Enterprise Architecture |",
        "| Approver | Architecture Board |",
        "| Status | 🟡 Draft |",
        f"| Last Review | {today} |",
        "| Next Review | auto |",
        "",
        "> Generated by `tools/ear_repo_check.py`. Do not edit manually.",
        "",
        "## Repository Health",
        "",
        f"**{stats['health']}%**",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Markdown files | {stats['total_md']} |",
        f"| Missing Metadata | {stats['missing_metadata']} |",
        f"| Incomplete Metadata | {stats['incomplete_metadata']} |",
        f"| Broken Links | {stats['broken_links']} |",
        f"| Review Due | {stats['review_due']} |",
        f"| Missing Owner | {stats['missing_owner']} |",
        f"| Missing README (numbered folders) | {stats['missing_readme']} |",
        f"| Unused Templates (heuristic) | {len(unused_templates)} |",
        f"| ADR records found | {len(adrs)} |",
        "",
        "## Inventory",
        "",
        "| Folder | Markdown Files | README |",
        "|---|---|---|",
    ]
    for name, count, has_readme in inventory:
        lines.append(f"| {name} | {count} | {'✅' if has_readme else '❌'} |")

    if missing_details["metadata"]:
        lines += ["", "## Missing Metadata", ""]
        lines += [f"- {x}" for x in missing_details["metadata"][:40]]
    if missing_details["incomplete"]:
        lines += ["", "## Incomplete Metadata Fields", ""]
        lines += [f"- {x}" for x in missing_details["incomplete"][:40]]
    if missing_details["broken"]:
        lines += ["", "## Broken Links", ""]
        lines += [f"- {x}" for x in missing_details["broken"][:40]]
    if missing_details["review_due"]:
        lines += ["", "## Review Due", ""]
        lines += [f"- {x}" for x in missing_details["review_due"][:40]]
    if unused_templates:
        lines += ["", "## Unused Templates (heuristic)", ""]
        lines += [f"- {x}" for x in unused_templates]

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def write_inventory(root: Path, inventory, stats):
    out = root / "00 Repository Guide" / "GENERATED_INVENTORY.md"
    lines = [
        "# Generated Inventory",
        "",
        "| Field | Value |",
        "|---|---|",
        "| ID | EAR-IDX-004 |",
        "| Version | 0.2 |",
        "| Owner | Automation |",
        "| Reviewer | PMO |",
        "| Approver | Enterprise Architecture |",
        "| Status | 🟡 Draft |",
        "| Last Review | auto |",
        "| Next Review | auto |",
        "",
        "> Generated by `tools/ear_repo_check.py`. Do not edit manually.",
        "",
        f"Repository Health: **{stats['health']}%**",
        "",
        "| Folder | Markdown Files | README |",
        "|---|---|---|",
    ]
    for name, count, has_readme in inventory:
        lines.append(f"| {name} | {count} | {'✅' if has_readme else '❌'} |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def write_adr_index(root: Path, adrs):
    out = root / "05 Architecture Decision Records" / "ADR_INDEX.generated.md"
    lines = [
        "# ADR Index (Generated)",
        "",
        "| Field | Value |",
        "|---|---|",
        "| ID | ADR-IDX-001 |",
        "| Version | 0.1 |",
        "| Owner | Automation |",
        "| Reviewer | Solution Architect |",
        "| Approver | Architecture Board |",
        "| Status | 🟡 Draft |",
        "| Last Review | auto |",
        "| Next Review | auto |",
        "",
        "> Generated by `tools/ear_repo_check.py`. Create real ADRs with ID `ADR-NNN`.",
        "",
        "| ADR | Title/File | Status | Owner | Last Review | Path |",
        "|---|---|---|---|---|---|",
    ]
    if not adrs:
        lines.append("| — | No ADR records yet | — | — | — | — |")
    else:
        for row in adrs:
            lines.append(
                f"| {row['id']} | {row['title']} | {row['status']} | {row['owner']} | {row['last_review']} | `{row['path']}` |"
            )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def main():
    parser = argparse.ArgumentParser(description="ECMP EAR self-governance checker")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--write-inventory", action="store_true")
    parser.add_argument("--write-health", action="store_true")
    parser.add_argument("--write-adr-index", action="store_true")
    parser.add_argument("--write-all", action="store_true", help="Write inventory + health + ADR index")
    parser.add_argument("--strict", action="store_true", help="Fail on missing/incomplete metadata")
    parser.add_argument("--fail-on-review-due", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    today = date.today()

    missing_metadata = []
    incomplete_metadata = []
    missing_owner = []
    review_due = []
    broken_links = []
    total_md = 0

    for path in iter_markdown_files(root):
        total_md += 1
        text = path.read_text(encoding="utf-8", errors="ignore")
        rel = path.relative_to(root).as_posix()
        meta = parse_metadata(text)

        if not meta.get("ID") or not meta.get("Status") or not meta.get("Owner"):
            missing_metadata.append(rel)
        else:
            missing_fields = [f for f in META_FIELDS if f not in meta or not meta[f]]
            if missing_fields:
                incomplete_metadata.append(f"{rel} ({', '.join(missing_fields)})")
            if not meta.get("Owner"):
                missing_owner.append(rel)
            next_review = parse_date(meta.get("Next Review", ""))
            if next_review and next_review < today:
                review_due.append(f"{rel} (Next Review {next_review.isoformat()})")

        for link in check_links(path, text):
            broken_links.append(f"{rel} -> {link}")

    inventory = build_inventory(root)
    missing_readme = sum(1 for _, _, has in inventory if not has)
    adrs = collect_adrs(root)
    _, unused_templates = template_usage(root)

    stats = {
        "total_md": total_md,
        "folders": len(inventory),
        "missing_metadata": len(missing_metadata),
        "incomplete_metadata": len(incomplete_metadata),
        "broken_links": len(broken_links),
        "review_due": len(review_due),
        "missing_owner": len(missing_owner),
        "missing_readme": missing_readme,
    }
    stats["health"] = score_health(stats)

    print("ECMP EAR Repository Health Check")
    print(f"Root: {root}")
    print(f"Repository Health: {stats['health']}%")
    print(f"Markdown files: {total_md}")
    print(f"Missing Metadata: {stats['missing_metadata']}")
    print(f"Incomplete Metadata: {stats['incomplete_metadata']}")
    print(f"Broken Links: {stats['broken_links']}")
    print(f"Review Due: {stats['review_due']}")
    print(f"Missing Owner: {stats['missing_owner']}")
    print(f"Missing README: {stats['missing_readme']}")
    print(f"ADR records: {len(adrs)}")
    print(f"Unused templates (heuristic): {len(unused_templates)}")

    missing_details = {
        "metadata": missing_metadata,
        "incomplete": incomplete_metadata,
        "broken": broken_links,
        "review_due": review_due,
    }

    if args.write_all or args.write_inventory:
        path = write_inventory(root, inventory, stats)
        print(f"Wrote {path}")
    if args.write_all or args.write_health:
        path = write_health_report(root, stats, inventory, missing_details, adrs, unused_templates)
        print(f"Wrote {path}")
    if args.write_all or args.write_adr_index:
        path = write_adr_index(root, adrs)
        print(f"Wrote {path}")

    fail = False
    if broken_links:
        fail = True
    if args.strict and (missing_metadata or incomplete_metadata or missing_readme):
        fail = True
    if args.fail_on_review_due and review_due:
        fail = True
    if fail:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
