#!/usr/bin/env python3
"""Feedback loop metrics: coverage delta, docs-sync signal, sprint readiness."""

from __future__ import annotations

import json
import re
from datetime import date

from eos_lib import ROOT, domain_signals, meta_block

HISTORY_DIR = ROOT / "metrics" / "history"
OUT = ROOT / "00 Repository Guide" / "FEEDBACK_METRICS.generated.md"
PORTAL = ROOT / "docs" / "governance" / "feedback-metrics.md"


def load_history():
    rows = []
    if not HISTORY_DIR.exists():
        return rows
    for path in sorted(HISTORY_DIR.glob("*.json")):
        try:
            rows.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            continue
    rows.sort(key=lambda r: r.get("date", ""))
    return rows


def coverage_snapshot():
    domains = ["CRM", "ECMF", "KPI", "Dashboard", "Notification", "Core Platform"]
    rows = []
    for d in domains:
        sig = domain_signals(d)
        avg = (sig["frd_score"] + sig["api_score"] + sig["event_score"] + sig["test_score"]) / 4
        rows.append({"domain": d, "avg": avg, **sig})
    overall = sum(r["avg"] for r in rows) / max(len(rows), 1)
    return rows, overall


def docs_sync_rate_from_ai_review() -> str:
    report = ROOT / "metrics" / "AI_REVIEW.generated.md"
    if not report.exists():
        return "n/a"
    text = report.read_text(encoding="utf-8", errors="ignore")
    if "Implementation files changed without documentation" in text:
        return "0% (last review warned docs drift)"
    if "_No git changes detected" in text:
        return "n/a (no local git diff)"
    # if implementation and docs both present in lanes, treat as synced signal
    has_impl = "### implementation" in text and "\n- `" in text.split("### implementation", 1)[-1].split("###", 1)[0]
    has_docs = any(x in text for x in ["### documentation", "### api_events", "### architecture"])
    if has_impl and has_docs:
        return "100% (last review shows impl+docs touched)"
    if has_impl and not has_docs:
        return "0% (impl without docs/catalog)"
    return "n/a"


def sprint_lead_time() -> str:
    sprint = ROOT / "ai" / "sprint" / "Sprint-01.md"
    if not sprint.exists():
        return "n/a"
    text = sprint.read_text(encoding="utf-8", errors="ignore")
    last = re.search(r"\|\s*Last Review\s*\|\s*([0-9-]{10})\s*\|", text)
    nxt = re.search(r"\|\s*Next Review\s*\|\s*([0-9-]{10})\s*\|", text)
    status = "Approved" if "Approved" in text or "🟢" in text else "Draft"
    if last and nxt:
        return f"Sprint-01 status={status}; planned window {last.group(1)} → {nxt.group(1)}"
    return f"Sprint-01 status={status}"


def main():
    rows, overall = coverage_snapshot()
    history = load_history()
    prev_overall = None
    # try read previous feedback snapshot if embedded in history
    if len(history) >= 2:
        prev = history[-2]
        prev_overall = prev.get("coverage_overall")

    delta = "n/a" if prev_overall is None else f"{overall - prev_overall:+.1f} pts"

    lines = [
        "# Feedback Metrics Loop",
        "",
        *meta_block("EOS-FB-001"),
        "> Generated by `tools/feedback_metrics.py`.",
        "",
        "## Development Effectiveness Signals",
        "",
        "| Signal | Value |",
        "|---|---|",
        f"| Domain coverage overall | {overall:.1f}% |",
        f"| Coverage delta vs previous metrics snapshot | {delta} |",
        f"| Docs-sync signal (from AI review) | {docs_sync_rate_from_ai_review()} |",
        f"| Sprint lead/window signal | {sprint_lead_time()} |",
        f"| Traceability links | {history[-1].get('traceability_links', 'n/a') if history else 'n/a'} |",
        f"| Reviewed docs % | {history[-1].get('reviewed_pct', 'n/a') if history else 'n/a'} |",
        "",
        "## Coverage by Domain",
        "",
        "| Domain | FRD | API | Event | Test | Avg |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: x["avg"]):
        lines.append(
            f"| {r['domain']} | {r['frd_score']}% | {r['api_score']}% | {r['event_score']}% | {r['test_score']}% | {r['avg']:.0f}% |"
        )

    lines += [
        "",
        "## How to use this loop",
        "",
        "1. Run before/after each sprint slice: `python tools/eos.py feedback`",
        "2. Watch coverage avg and docs-sync warnings",
        "3. Prefer improving lowest domain avg before expanding scope",
        "4. Keep Sprint DoD tied to tests + catalog sync + health check",
        "",
    ]
    text = "\n".join(lines)
    OUT.write_text(text, encoding="utf-8")
    PORTAL.parent.mkdir(parents=True, exist_ok=True)
    PORTAL.write_text(text, encoding="utf-8")

    # enrich today's metrics snapshot
    today = date.today().isoformat()
    snap = HISTORY_DIR / f"{today}.json"
    if snap.exists():
        data = json.loads(snap.read_text(encoding="utf-8"))
        data["coverage_overall"] = round(overall, 2)
        data["docs_sync_signal"] = docs_sync_rate_from_ai_review()
        snap.write_text(json.dumps(data, indent=2), encoding="utf-8")

    print(f"Wrote {OUT}")
    print(f"coverage_overall={overall:.1f}% delta={delta}")


if __name__ == "__main__":
    main()
