#!/usr/bin/env python3
"""Impact Analysis Engine: given an ID, show downstream/upstream impacts."""

from __future__ import annotations

import argparse

from eos_lib import ROOT, load_traceability, meta_block

OUT = ROOT / "26 Traceability" / "IMPACT_ANALYSIS.generated.md"


def normalize(token: str) -> str:
    return token.strip().upper()


def collect_impact(target: str):
    links, artifacts = load_traceability()
    t = normalize(target)
    matched = []
    for link in links:
        bag = {
            normalize(link.get("bp", "")),
            normalize(link.get("br", "")),
            normalize(link.get("fr", "")),
            normalize(link.get("sprint", "")),
            normalize(link.get("domain", "")),
        }
        bag.update(normalize(x) for x in (link.get("api") or []))
        bag.update(normalize(x) for x in (link.get("events") or []))
        bag.update(normalize(x) for x in (link.get("tests") or []))
        if t in bag:
            matched.append(link)

    impacted = {
        "domains": set(),
        "bp": set(),
        "br": set(),
        "fr": set(),
        "api": set(),
        "events": set(),
        "tests": set(),
        "sprints": set(),
        "links": matched,
    }
    for link in matched:
        impacted["domains"].add(link.get("domain"))
        impacted["bp"].add(link.get("bp"))
        impacted["br"].add(link.get("br"))
        impacted["fr"].add(link.get("fr"))
        impacted["api"].update(link.get("api") or [])
        impacted["events"].update(link.get("events") or [])
        impacted["tests"].update(link.get("tests") or [])
        if link.get("sprint"):
            impacted["sprints"].add(link.get("sprint"))
    return impacted, artifacts


def render(target: str, impacted, artifacts) -> str:
    def label(kind, _id):
        return artifacts.get(kind, {}).get(_id, "")

    lines = [
        f"# Impact Analysis — `{target}`",
        "",
        *meta_block("EOS-IMPACT-001"),
        f"> Generated by `tools/impact_analysis.py --id {target}`",
        "",
        "## Impact Chain",
        "",
        "```text",
        f"{target}",
        "   │",
        "   ├─ FRD: " + ", ".join(sorted(impacted["fr"]) or ["—"]),
        "   ├─ API: " + ", ".join(sorted(impacted["api"]) or ["—"]),
        "   ├─ Event: " + ", ".join(sorted(impacted["events"]) or ["—"]),
        "   ├─ Test Case: " + ", ".join(sorted(impacted["tests"]) or ["—"]),
        "   └─ Sprint: " + ", ".join(sorted(impacted["sprints"]) or ["—"]),
        "```",
        "",
        "## Summary",
        "",
        f"- Domains: {', '.join(sorted(x for x in impacted['domains'] if x)) or '—'}",
        f"- Links matched: {len(impacted['links'])}",
        "",
        "## FRD Impacted",
        "",
    ]
    for fr in sorted(impacted["fr"]):
        lines.append(f"- `{fr}` — {label('fr', fr)}")
    if not impacted["fr"]:
        lines.append("- —")

    sections = [
        ("Business Rules", "br", impacted["br"]),
        ("API", "api", impacted["api"]),
        ("Events", "events", impacted["events"]),
        ("Tests", "tests", impacted["tests"]),
        ("Blueprint Items", "bp", impacted["bp"]),
    ]
    for title, kind, values in sections:
        lines += ["", f"## {title}", ""]
        if not values:
            lines.append("- —")
            continue
        for item in sorted(values):
            lines.append(f"- `{item}` — {label(kind if kind != 'events' else 'events', item)}")

    lines += ["", "## Sprints", ""]
    if impacted["sprints"]:
        for s in sorted(impacted["sprints"]):
            lines.append(f"- `{s}`")
    else:
        lines.append("- —")

    lines += ["", "## Traceability Links", ""]
    if not impacted["links"]:
        lines.append("_No links found. Add relationships in `26 Traceability/traceability.yaml`._")
    else:
        for link in impacted["links"]:
            lines.append(
                f"- `{link.get('id')}` [{link.get('domain')}] {link.get('description')} "
                f"(status: {link.get('status')})"
            )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="ECMP Impact Analysis Engine")
    parser.add_argument("--id", required=True, help="Artifact ID, e.g. BR-001, API-001, EVT-002")
    parser.add_argument("--write", action="store_true", help="Write IMPACT_ANALYSIS.generated.md")
    args = parser.parse_args()

    impacted, artifacts = collect_impact(args.id)
    report = render(args.id, impacted, artifacts)
    if args.write:
        OUT.write_text(report, encoding="utf-8")
        print(f"Wrote {OUT}")
    else:
        try:
            print(report)
        except UnicodeEncodeError:
            print(report.encode("ascii", errors="replace").decode("ascii"))


if __name__ == "__main__":
    main()
