#!/usr/bin/env python3
"""Search local RAG index and optionally write context pack."""

from __future__ import annotations

import argparse

from eos_lib import ROOT, meta_block
from rag_lib import search

OUT = ROOT / "ai" / "rag" / "last_context.md"


def main():
    parser = argparse.ArgumentParser(description="ECMP RAG search")
    parser.add_argument("--query", required=True)
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--collection", default=None)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    hits = search(args.query, top_k=args.top_k, collection=args.collection)
    if not hits:
        print("No results.")
        return

    lines = [
        f"# RAG Context — {args.query}",
        "",
        *meta_block("RAG-CTX-001"),
        f"> Generated by `tools/rag_search.py --query \"{args.query}\"`",
        "",
        f"Results: {len(hits)}",
        "",
    ]
    for i, hit in enumerate(hits, 1):
        print(f"{i}. [{hit['score']}] {hit['path']} ({hit['collection']})")
        lines += [
            f"## Hit {i}: `{hit['path']}` (score={hit['score']}, {hit['collection']})",
            "",
            hit["text"],
            "",
            "---",
            "",
        ]
    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
