#!/usr/bin/env python3
"""Repository Metrics with historical snapshot."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from eos_lib import (
    ROOT,
    list_adrs,
    list_events,
    list_openapi_ops,
    load_traceability,
    meta_block,
)
from repo_check_lib import (
    META_FIELDS,
    build_inventory,
    check_links,
    iter_markdown_files,
    parse_metadata,
    score_health,
)

OUT = ROOT / "00 Repository Guide" / "REPO_METRICS.generated.md"
HISTORY_DIR = ROOT / "metrics" / "history"
PORTAL = ROOT / "docs" / "governance" / "repo-metrics.md"


def count_reviewed(root: Path) -> tuple[int, int]:
    total = 0
    reviewed = 0
    for path in iter_markdown_files(root):
        if "generated" in path.name.lower() or path.name.startswith("GENERATED"):
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        meta = parse_metadata(text)
        if not meta:
            continue
        total += 1
        status = (meta.get("Status") or "").lower()
        if "approved" in status:
            reviewed += 1
    return reviewed, total


def main():
    links, artifacts = load_traceability()
    root = ROOT

    missing_metadata = 0
    incomplete = 0
    broken = 0
    total_md = 0
    for path in iter_markdown_files(root):
        total_md += 1
        text = path.read_text(encoding="utf-8", errors="ignore")
        meta = parse_metadata(text)
        if not meta.get("ID") or not meta.get("Status") or not meta.get("Owner"):
            missing_metadata += 1
        else:
            if any(f not in meta or not meta[f] for f in META_FIELDS):
                incomplete += 1
        broken += len(check_links(path, text))

    inventory = build_inventory(root)
    missing_readme = sum(1 for _, _, has in inventory if not has)
    stats = {
        "total_md": total_md,
        "folders": len(inventory),
        "missing_metadata": missing_metadata,
        "incomplete_metadata": incomplete,
        "broken_links": broken,
        "review_due": 0,
        "missing_owner": 0,
        "missing_readme": missing_readme,
    }
    health = score_health(stats)
    reviewed, reviewed_total = count_reviewed(root)
    metadata_complete_pct = int(round(100 * (1 - (missing_metadata + incomplete) / max(total_md, 1))))
    reviewed_pct = int(round(100 * reviewed / max(reviewed_total, 1)))

    snapshot = {
        "date": date.today().isoformat(),
        "health": health,
        "markdown_files": total_md,
        "adr_count": len(list_adrs()),
        "api_spec_count": len(list_openapi_ops()),
        "event_count": len(list_events()),
        "business_rules_referenced": len(artifacts.get("br", {})),
        "fr_referenced": len(artifacts.get("fr", {})),
        "domains_in_traceability": len({ln.get("domain") for ln in links}),
        "traceability_links": len(links),
        "metadata_complete_pct": metadata_complete_pct,
        "reviewed_pct": reviewed_pct,
    }

    HISTORY_DIR.mkdir(parents=True, exist_ok=True)
    hist_file = HISTORY_DIR / f"{snapshot['date']}.json"
    hist_file.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")

    lines = [
        "# Repository Metrics",
        "",
        *meta_block("EOS-METRICS-001"),
        "> Generated by `tools/repo_metrics.py`.",
        "",
        f"## Snapshot ({snapshot['date']})",
        "",
        f"**Repository Health: {health}%**",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| ADR count | {snapshot['adr_count']} |",
        f"| API specs | {snapshot['api_spec_count']} |",
        f"| Events | {snapshot['event_count']} |",
        f"| Business Rules (referenced) | {snapshot['business_rules_referenced']} |",
        f"| FR (referenced) | {snapshot['fr_referenced']} |",
        f"| Domains in traceability | {snapshot['domains_in_traceability']} |",
        f"| Traceability links | {snapshot['traceability_links']} |",
        f"| Metadata completeness | {metadata_complete_pct}% |",
        f"| Approved/reviewed docs | {reviewed_pct}% ({reviewed}/{reviewed_total}) |",
        f"| Markdown files | {total_md} |",
        f"| Broken links | {broken} |",
        "",
        f"History file: `metrics/history/{snapshot['date']}.json`",
        "",
    ]
    text = "\n".join(lines)
    OUT.write_text(text, encoding="utf-8")
    PORTAL.parent.mkdir(parents=True, exist_ok=True)
    PORTAL.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Wrote {PORTAL}")
    print(f"Wrote {hist_file}")


if __name__ == "__main__":
    main()
