#!/usr/bin/env python3
"""Aggregate AI telemetry runs into a summary report."""

from __future__ import annotations

import json

from aip_lib import AIP
from eos_lib import ROOT, meta_block

RUNS = AIP / "telemetry" / "runs"
OUT = AIP / "telemetry" / "reports" / "TELEMETRY_REPORT.generated.md"
PORTAL = ROOT / "docs" / "ai" / "telemetry.md"


def main():
    files = sorted(RUNS.glob("*.json")) if RUNS.exists() else []
    rows = []
    for path in files[-200:]:
        try:
            rows.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            continue

    total = len(rows)
    success = sum(1 for r in rows if r.get("success"))
    by_cap = {}
    rag_hits = []
    for r in rows:
        cap = r.get("capability_id", "unknown")
        by_cap.setdefault(cap, {"total": 0, "success": 0, "rag": []})
        by_cap[cap]["total"] += 1
        by_cap[cap]["success"] += 1 if r.get("success") else 0
        if "rag_top_score" in r:
            by_cap[cap]["rag"].append(float(r.get("rag_top_score") or 0))
            rag_hits.append(float(r.get("rag_top_score") or 0))

    rag_hit_rate = 0.0
    if rag_hits:
        rag_hit_rate = sum(1 for x in rag_hits if x > 0) / len(rag_hits)

    lines = [
        "# AI Telemetry Report",
        "",
        *meta_block("AIP-TEL-001"),
        "> Generated by `tools/telemetry_report.py`.",
        "",
        "## Overview",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Orchestrator routes logged | {total} |",
        f"| Success rate | {(success/max(total,1)):.0%} |",
        f"| RAG hit rate (top_score>0) | {rag_hit_rate:.0%} |",
        f"| Avg RAG top score | {(sum(rag_hits)/len(rag_hits) if rag_hits else 0):.3f} |",
        "",
        "## By Capability",
        "",
        "| Capability | Runs | Success | Avg RAG score |",
        "|---|---|---|---|",
    ]
    if not by_cap:
        lines.append("| — | 0 | n/a | n/a |")
    else:
        for cap, stat in sorted(by_cap.items()):
            avg_rag = sum(stat["rag"]) / len(stat["rag"]) if stat["rag"] else 0
            lines.append(
                f"| `{cap}` | {stat['total']} | {stat['success']/max(stat['total'],1):.0%} | {avg_rag:.3f} |"
            )

    lines += [
        "",
        "## Notes",
        "",
        "- Response latency/token size require live LLM instrumentation (next iteration).",
        "- Current telemetry captures orchestrator routing quality and RAG usefulness proxies.",
        "",
    ]
    text = "\n".join(lines)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    PORTAL.parent.mkdir(parents=True, exist_ok=True)
    PORTAL.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT} (routes={total})")


if __name__ == "__main__":
    main()
