"""Queue Application layer (TASK-062 / TASK-064 / CAPABILITY-003).

CQRS commands / queries + domain service + persistence-backed CRUD / Operations.
In-memory handlers remain for foundation workspace.
REST CRUD → QueueCrudApplicationService.
REST Operations → QueueOperationsApplicationService.
"""

from app.modules.queue.application.commands import (
    CallNextTicketCommand,
    CallNextTicketHandler,
    CancelTicketCommand,
    CancelTicketHandler,
    CloseQueueCommand,
    CloseQueueHandler,
    CompleteTicketCommand,
    CompleteTicketHandler,
    CreateQueueCommand,
    CreateQueueHandler,
    IssueTicketCommand,
    IssueTicketHandler,
    OpenQueueCommand,
    OpenQueueHandler,
    PauseQueueCommand,
    PauseQueueHandler,
    RecallTicketCommand,
    RecallTicketHandler,
    SkipTicketCommand,
    SkipTicketHandler,
)
from app.modules.queue.application.dto import (
    QueueCounterDto,
    QueueDto,
    QueueTicketDto,
)
from app.modules.queue.application.queries import (
    GetQueueHandler,
    GetQueueQuery,
    GetQueueTicketsHandler,
    GetQueueTicketsQuery,
    GetWaitingTicketsHandler,
    GetWaitingTicketsQuery,
)
from app.modules.queue.application.services import (
    CreateCounterInput,
    CreateQueueInput,
    InMemoryQueueState,
    IssueTicketInput,
    IssueTicketOperationInput,
    QueueApplicationError,
    QueueCounterView,
    QueueCrudApplicationService,
    QueueDomainService,
    QueueOperationsApplicationService,
    UpdateCounterInput,
    UpdateQueueInput,
    UpdateTicketInput,
    get_queue_domain_service,
    get_queue_state,
)

__all__ = [
    "CallNextTicketCommand",
    "CallNextTicketHandler",
    "CancelTicketCommand",
    "CancelTicketHandler",
    "CloseQueueCommand",
    "CloseQueueHandler",
    "CompleteTicketCommand",
    "CompleteTicketHandler",
    "CreateCounterInput",
    "CreateQueueCommand",
    "CreateQueueHandler",
    "CreateQueueInput",
    "GetQueueHandler",
    "GetQueueQuery",
    "GetQueueTicketsHandler",
    "GetQueueTicketsQuery",
    "GetWaitingTicketsHandler",
    "GetWaitingTicketsQuery",
    "InMemoryQueueState",
    "IssueTicketCommand",
    "IssueTicketHandler",
    "IssueTicketInput",
    "IssueTicketOperationInput",
    "OpenQueueCommand",
    "OpenQueueHandler",
    "PauseQueueCommand",
    "PauseQueueHandler",
    "QueueApplicationError",
    "QueueCounterDto",
    "QueueCounterView",
    "QueueCrudApplicationService",
    "QueueDomainService",
    "QueueDto",
    "QueueOperationsApplicationService",
    "QueueTicketDto",
    "RecallTicketCommand",
    "RecallTicketHandler",
    "SkipTicketCommand",
    "SkipTicketHandler",
    "UpdateCounterInput",
    "UpdateQueueInput",
    "UpdateTicketInput",
    "get_queue_domain_service",
    "get_queue_state",
]
